name: Publish to Test PyPI
run-name: Publish to Test PyPI triggered by ${{ github.ref_type }} ${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  upload_pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Test
        run: |
          python -m pytest

      - name: Build
        run: |
          python3 -m pip install --upgrade build && python3 -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          verify-metadata: false
